disabled_rules:
  - identifier_name
  - trailing_whitespace
  - trailing_comma
  - trailing_newline
  - switch_case_alignment
  - shorthand_operator

opt_in_rules:
  - empty_count

included:
  - Gom4ziz/Source
  - Gom4zizTests/Source

excluded:
  - Gom4ziz/Source/Presenter/Component/AsyncImageView.swift

line_length:
    warning: 240
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true
    ignores_urls: true
