name: Refactoring Template
description: 리팩토링 작업할 때 쓰는 템플릿
title: "[refactor]: Feature Title"
labels: ["refactor"]

body:
  - type: textarea
    id: refactor-contents
    attributes:
      label: Refactoring 설명
      description: 작업할 refactoring에 대한 설명을 적어주세요.
      placeholder: ex. 함수 래핑하기
    validations:
      required: true
      
  - type: input
    id: prepare-issue
    attributes:
      label: Prepare Issue(Optional)
      description: 관련된 Prepare가 있다면 적어주세요.
      placeholder: "ex. #14"
    validations:
      required: false

  - type: textarea
    id: related-view
    attributes:
      label: Related View(Optional)
      description: 작업하는 사항에 영향을 받는 View(화면)
      placeholder: ex. HomeView
    validations:
      required: false
